from aspects.analysis.aspects_hierarchy import AspectHierarchyRST

amazon_cellphone_aspect_hierarchy_100000_reviews = [
    AspectHierarchyRST(nucleus=u'phone', satellite=u'case', all_relations=633),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'battery', all_relations=448),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'headset', all_relations=322),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'charger', all_relations=270),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'price', all_relations=266),
    AspectHierarchyRST(nucleus=u'battery', satellite=u'charge', all_relations=183),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'camera', all_relations=176),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'screen', all_relations=162),
    # AspectHierarchyRST(nucleus=u'price', satellite=u'battery', all_relations=159),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'quality', all_relations=124),
    # AspectHierarchyRST(nucleus=u'case', satellite=u'price', all_relations=123),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'bluetooth', all_relations=117),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'reception', all_relations=112),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'battery life', all_relations=110),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'sound', all_relations=105),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'sound quality', all_relations=101),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'bluetooth', all_relations=100),
    # AspectHierarchyRST(nucleus=u'price', satellite=u'charger', all_relations=94),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'cover', all_relations=92),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'service', all_relations=91),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'price', all_relations=91),
    AspectHierarchyRST(nucleus=u'case', satellite=u'clip', all_relations=88),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'quality', all_relations=83),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'use', all_relations=77),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'volume', all_relations=74),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'color', all_relations=70),
    AspectHierarchyRST(nucleus=u'case', satellite=u'design', all_relations=67),
    AspectHierarchyRST(nucleus=u'case', satellite=u'color', all_relations=64),
    AspectHierarchyRST(nucleus=u'case', satellite=u'leather', all_relations=62),
    AspectHierarchyRST(nucleus=u'case', satellite=u'protection', all_relations=61),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'sound', all_relations=60),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'use', all_relations=60),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'car charger', all_relations=60),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'signal', all_relations=59),
    AspectHierarchyRST(nucleus=u'case', satellite=u'quality', all_relations=58),
    AspectHierarchyRST(nucleus=u'case', satellite=u'belt', all_relations=58),
    # AspectHierarchyRST(nucleus=u'case', satellite=u'screen', all_relations=56),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'size', all_relations=55),
    # AspectHierarchyRST(nucleus=u'charger', satellite=u'charge', all_relations=51),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'bluetooth headset', all_relations=48),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'battery', all_relations=42),
    AspectHierarchyRST(nucleus=u'headset', satellite=u'battery life', all_relations=39),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'speaker', all_relations=34),

    # AspectHierarchyRST(nucleus=u'phone', satellite=u'game', all_relations=47),
    AspectHierarchyRST(nucleus=u'case', satellite=u'pocket', all_relations=47),
    # AspectHierarchyRST(nucleus=u'phone', satellite=u'hand', all_relations=46),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'light', all_relations=46),
    # AspectHierarchyRST(nucleus=u'charger', satellite=u'cord', all_relations=44),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'car', all_relations=43),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'video', all_relations=39),
    # AspectHierarchyRST(nucleus=u'phone', satellite=u'card', all_relations=39),
    # AspectHierarchyRST(nucleus=u'headset', satellite=u'hour', all_relations=37),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'menu', all_relations=37),
    AspectHierarchyRST(nucleus=u'phone', satellite=u'display', all_relations=37),
    AspectHierarchyRST(nucleus=u'product', satellite=u'complaint', all_relations=33)
]
